### ISSUE TITLE
Min Java SDK at 1.7 or 1.8?

### ISSUE THREAD

**Issue by chalin** [grpc/grpc-kotlin#191]
We follow gRPC Java in **requiring JDK 7+**, as [specified in the Quick start, for example](https://grpc.io/docs/languages/kotlin/quickstart/#prerequisites):

> <img src="https://user-images.githubusercontent.com/4140793/96599176-a453b400-12bd-11eb-9a12-30aaf8dcbf3f.png" width=230>

I've noticed that in some of the `examples/stub*/build.gradle.kts` files, the `sourceCompatibility` is set to 1.8; for example: https://github.com/grpc/grpc-kotlin/blob/6c6078ca648c4bc7cc24224578fb46427970afb9/examples/stub/build.gradle.kts#L26

My questions:

- Should this be 1.7?
- Why isn't the same setting used in `stub-android/build.gradle.kts`?

cc @bshaffer

**Comment by jamesward** [comment]
I used JDK 8 in the samples so that we can use `kotlin("stdlib-jdk8")` but we probably aren't taking advantage of anything in there so we can see about just using `kotlin("stdlib")` which I think is JDK 7 compatible.

We aren't really using the Java stuff in the Android sample which is why we don't need to set java settings.

**Comment by chalin** [comment]
Thanks for the explanation. @jamesward, can you make this change in the example config?
