### ISSUE TITLE
SharedFlow causes GRPC to duplicate headers

### ISSUE THREAD

**Issue by ReginFell** [grpc/grpc-kotlin#208]
Hello, we encountered an issue when try to use `grpc-kotlin` with `SharedFlow`, 

Our use case is: 
```
grpcStub.observeEvents()
   .shareIn(scope, started = SharingStarted.WhileSubscribed())
```

And first time everything is OK, but once `SharedFlow` does not have any subscribers it completes itself. After that if we resubscribe to it, Metadata object will contain all headers from the previous connection. 

So next time `ClientsCalls.kt -> rpcImpl` will invoke `clientCall.start` with outdated meta info.

Any ideas how it can be solved? 
Thanks

**Comment by lowasser** [comment]
It's not clear to me what you want to happen here.  Do you want the metadata to be created fresh?  Or do you want the `SharedFlow` to keep going after all the subscribers leave?

**Comment by lowasser** [comment]
`observeEvents()` can't, I think, be code that's generated by gRPC-Kotlin, because all of those methods should have at least one argument.  So it's not clear to me where the metadata object is being created, but if you wanted the metadata to be created fresh, you could probably write

```
flow {
  emitAll(grpcStub.observeEvents(Metadata()))
}.shareIn(...)
```

...which just recreates the `Metadata` object each time the flow is started.

If what you want is for the flow to keep going after the subscribers leave, then you just change the `started` parameter appropriately.

**Comment by ReginFell** [comment]
Yes, the real code has `request`, tried to simplify to keep it focused.

In fact it is something like

```
grpcStub.observeEvents(Request.Empty)
   .shareIn(scope, started = SharingStarted.WhileSubscribed())
.collect {...} 
```

So what we have expected, that with SharedFlow coroutines stub will work the same as with regular flow, each time we subscribe, we receive complety new flow with fresh Metadata but in fact Metadata object is cached. 

The workaround
```
flow {
  emitAll(grpcStub.observeEvents(Request.Empty))
}.shareIn(...)
```
Will work, but should not it be a part of the library to prevent this from happening?

**Comment by lowasser** [comment]
The issue is really that `Metadata` is mutable, I think, which isn't a choice made by the Kotlin layer.  Maybe we could make a fresh copy of the Metadata for each invocation of the flow?  I don't know if that'd break any other code's expectations...

**Comment by mrgoltstein** [comment]
Hi 👋 I'm a colleague of @ReginFell. Thank you for taking the time to help us out.

To add a little bit more context: in our codebase we have a `ClientInterceptor` that adds an authentication token to the `Metadata`. In the above-mentioned situation gRPC calls will already contain the (potentially outdated) authentication token, while, as you suspected, what we expected was an empty instance of `Metadata`. 

> Maybe we could make a fresh copy of the Metadata for each invocation of the flow?  I don't know if that'd break any other code's expectations...
This would resolve the issue for our use-case, which I think is a common use-case especially on mobile devices: when a user closes the app and reopens within a certain timeframe we want them to resume where they left off rather than disconnect & reconnect, to save resources.

I don't know what use-cases others have, that would expect to receive the same `Metadata` instance across gRPC calls. However I would argue that since `Metadata` is information about a particular call, one could (should?) expect to receive a fresh instance with every API invocation.
