### ISSUE TITLE
Intellij + Bazel plugin reports "Cannot access 'io.grpc.kotlin.AbstractCoroutineServerImpl'" while the code builds and runs

### ISSUE THREAD

**Issue by wjf3121** [grpc/grpc-kotlin#248]
HI all,

I'm working on a Kotlin gRPC project using Intellij + Bazel plugin. I got this error message about my service class in Intellij while the code can build and run using "bazel buiid/run":

Cannot access 'io.grpc.kotlin.AbstractCoroutineServerImpl' which is a supertype of 'MY_SERVICE_CLASS'. Check your module classpath for missing or conflicting dependencies

Any idea what I might miss to make Intellij + Bazel plugin work with my project? Thanks!

**Comment by jamesward** [comment]
Maybe @lowasser knows something about this?

**Comment by wjf3121** [comment]
Kindly ping

**Comment by Kernald** [comment]
I might be wrong, but this sounds like an issue with the Kotlin rules or the IntelliJ plugin rather than gRPC-Kotlin. Which version of the Kotlin rules are you using?

**Comment by wjf3121** [comment]
Hi Kernald,

Thanks for the reply!  Regarding Kotlin rules I'm using rules_kotlin-legacy-1.3.0. And the Kotlin Intellij Version is 202-1.4.32-release-IJ8194.7

**Comment by Kernald** [comment]
This is most likely an issue with the Kotlin rules then. This is something that has been improved quite a lot recently. I remember someone mentioning plans for a stable release soon, but in the meantime, I'd try the latest pre-release to see if it improves things - at least to confirm that this issue comes from there and nothing gRPC-Kotlin specific.

**Comment by wjf3121** [comment]
I see, will upgrade the Kotlin rules and report back the result. Thanks for you help!

**Comment by metalLeveller** [comment]
Hi all,

have the same error in Idea, but using Gradle instead of Bazel.

@wjf3121 did you succeed with the rules?

**Comment by wjf3121** [comment]
Upgrading the bazel plugin to the latest version(Version 2021.04.27.0.0) solves the issue.

**Comment by sgc109** [comment]
I came across this issue when using Gradle and IntelliJ, but it turned out there was no dependency for `grpc-kotlin-stub` after I increased a version of my custom module including `grpc-kotlin-stub`.
So, I resolved this issue by adding `implementation("io.grpc:grpc-kotlin-stub:1.2.1")` to gradle's build script.
