### ISSUE TITLE
Why cast to status exception when not status.isOk ?

### ISSUE THREAD

**Issue by sangyongchoi** [grpc/grpc-kotlin#347]
Hi, i got curious while using grpc-kotlin
this is "Why cast to status exception when not status.isOk ?"
io.grpc.kotlin.ClientCalls 295 line.
Should you tell me reason that cast StatusException not StatusRuntimeException.

I issue here because not response where grpc-group.
Could you please tell me the solution when you have a chance?

**Comment by j-min5u** [comment]
I've also noticed this too recently while migrating a kotlin test to java. But since [Kotlin does not have checked exceptions](https://kotlinlang.org/docs/exceptions.html#checked-exceptions), would there be reason to differentiate StatusException & StatusRuntimeException? Also, this fix would be breaking change on gRPC stub behavior.

**Comment by sangyongchoi** [comment]
@j-min5u I think it's right to show the error sent by the server.
It is just my opinion, I send StatusRuntimeException, but it did StatusException and it was unnatural.
So I was curious, why cast to StatusException not StatusRuntimeException.
