### ISSUE TITLE
Can't build gRPC project with Docker

### ISSUE THREAD

**Issue by luccasmf** [grpc/grpc-kotlin#361]
Hey there, I'm struggling to build a Kotlin+Micronaut+gRPC project with a dockerfile.

By running it from IDE or with "gradle assemble" it runs smoothly, but, everytime I try to build my Docker image I get the same error on the assemble Step

`> java.io.IOException: Cannot run program "/home/gradle/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protoc/3.20.1/e76503532564f10b5ab127b14c41d80d166602bc/protoc-3.20.1-linux-x86_64.exe": error=2, No such file or directory`

Here is my Dockerfile (the newrelic part works like a charm)

```FROM gradle:7.5.1-jdk18-alpine AS build

WORKDIR /data
COPY . /data

RUN apk update && apk add curl unzip --no-cache protoc
RUN curl -O https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-java.zip
RUN unzip -q newrelic-java.zip
RUN gradle assemble --no-daemon```

**Comment by jamesward** [comment]
Seems like that binary can't be run.  You'll probably need to do some debugging to figure out why, ie get a cmd line shell into the container and try to run it.  One possibility is that the executable for some reason isn't set to be executable.  I don't know if there is much more we can help with since we don't have a good way to reproduce this.
BTW, You don't need to apk install protoc since that comes through Gradle.

**Comment by jamesward** [comment]
This might help: https://github.com/google/protobuf-gradle-plugin/issues/265

**Comment by luccasmf** [comment]
@jamesward you rock, it looks like it worked, the image was built,
