### ISSUE TITLE
[Feature request] Rx-Java support

### ISSUE THREAD

**Issue by st0rmr1der1994** [grpc/grpc-kotlin#78]
Can you please implement Rx-Java support for grpc stubs in future to have possibility use coroutines or Rx?

**Comment by gary-lo** [comment]
If you're looking to use Rx-Java I think this will work better - and since it's interoperable with Kotlin it probably belongs better there: https://github.com/salesforce/reactive-grpc

Depending on what you mean the stubs already generate out suspend functions. This resource might help: https://www.cncf.io/webinars/announcing-open-source-grpc-kotlin/

**Comment by lowasser** [comment]
We recommend using https://github.com/Kotlin/kotlinx.coroutines/tree/master/reactive/kotlinx-coroutines-rx2 to adapt between coroutines and Rx.
